(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(comint-terminfo-terminal "xterm-256color")
 '(dashboard-buffer-last-width 214)
 '(diredc-shell-default "zsh shell")
 '(doom-modeline-gnus-timer 0)
 '(elpy-rpc-python-command "python3")
 '(eww-bookmarks-directory "~/.emacs.d/private/")
 '(exec-path
   '("/bin/" "/usr/bin/" "/usr/local/bin/" "/usr/local/texlive/bin/" "/opt/local/bin/" "/Library/TeX/texbin/" "/usr/sbin/" "/sbin/" "/opt/X11/bin/" "/Applications/Emacs.app/Contents/MacOS/libexec/" "/usr/local/Cellar/pyenv-virtualenv/1.1.5/shims/" "/usr/local/opt/coreutils/libexec/gnubin/"))
 '(file-template-insert-automatically t)
 '(flycheck-checker-error-threshold nil)
 '(focus-follows-mouse 'auto-raise)
 '(font-latex-fontify-sectioning 1.2)
 '(helm-allow-mouse t)
 '(is-all-the-icons-installed t)
 '(mouse-wheel-progressive-speed nil)
 '(mouse-yank-at-point t)
 '(nxml-bind-meta-tab-to-complete-flag nil)
 '(org-adapt-indentation nil)
 '(org-agenda-entry-text-maxlines 10)
 '(org-agenda-files
   '("~/Dropbox/org/agenda/organizer.org" "~/Dropbox/org/agenda/contacts.org" "~/Dropbox/org/agenda/Notes.org" "~/Dropbox/org/agenda/opgaver.org"))
 '(org-agenda-include-diary t)
 '(org-agenda-inhibit-startup t)
 '(org-agenda-insert-diary-strategy 'date-tree-last)
 '(org-agenda-loop-over-headlines-in-active-region nil)
 '(org-agenda-prefix-format
   '((agenda . " %i %-10:c%?-12t% s")
     (timeline . "  % s")
     (todo . " %i %-14:c")
     (tags . " %i %-14:c")
     (search . " %i %-14:c")))
 '(org-agenda-span 14)
 '(org-agenda-tags-column -100)
 '(org-agenda-time-leading-zero t)
 '(org-agenda-use-tag-inheritance t)
 '(org-capture-bookmark nil)
 '(org-catch-invisible-edits 'smart)
 '(org-confirm-babel-evaluate nil)
 '(org-deadline-warning-days 7)
 '(org-default-notes-file "~/Dropbox/org/agenda/Notes.org")
 '(org-directory "~/Dropbox/org/")
 '(org-ellipsis " ⤵")
 '(org-enforce-todo-dependencies t)
 '(org-expiry-inactive-timestamps t)
 '(org-export-creator-string "\\tiny{Emacs 28.0.50 (Org mode 9.4.4)}")
 '(org-export-default-language "da")
 '(org-export-with-archived-trees nil)
 '(org-export-with-drawers '("HIDE"))
 '(org-export-with-section-numbers nil)
 '(org-export-with-sub-superscripts nil)
 '(org-export-with-tags 'not-in-toc)
 '(org-fancy-priorities-list '(" " " " " " " "))
 '(org-footnote-auto-adjust 'renumber)
 '(org-hidden-keywords '(email subtitle))
 '(org-hide-emphasis-markers t)
 '(org-id-link-to-org-use-id t)
 '(org-id-locations-file "~/.emacs.d/private/.org-id-locations")
 '(org-image-actual-width nil)
 '(org-indirect-buffer-display 'current-window)
 '(org-latex-compiler "lualatex")
 '(org-latex-listings t)
 '(org-latex-pdf-process '("latexmk -lualatex -recorder -synctex=1 -bibtex-cond %b"))
 '(org-link-translation-function 'toc-org-unhrefify)
 '(org-log-done 'time)
 '(org-log-into-drawer "LOGBOOK")
 '(org-mac-iCal-import-exchange t)
 '(org-open-directory-means-index-dot-org t)
 '(org-outline-path-complete-in-steps nil)
 '(org-pretty-entities t)
 '(org-pretty-tags-global-mode 1)
 '(org-pretty-tags-mode-lighter " 📤")
 '(org-read-date-prefer-future nil)
 '(org-refile-allow-creating-parent-nodes 'confirm)
 '(org-refile-target-verify-function 'bh/verify-refile-target)
 '(org-refile-use-outline-path t)
 '(org-remove-highlights-with-change nil)
 '(org-return-follows-link t)
 '(org-roam-buffer-position 'left)
 '(org-roam-buffer-width 0.25)
 '(org-roam-db-update-idle-seconds 300)
 '(org-roam-db-update-method 'immediate)
 '(org-roam-directory "/Users/niels/Dropbox/org/roam/")
 '(org-roam-doctor-inhibit-startup nil)
 '(org-roam-graph-exclude-matcher
   '("archive" "PRIVAT" "blog" "books" "agenda" "include" "elfeed" "Documentation" "auto" "elfeed" "init" "journal" "regularly" "tasks" "work"))
 '(org-roam-graph-executable "/usr/local/bin/dot")
 '(org-roam-graph-viewer nil)
 '(org-roam-index-file "/Users/niels/Dropbox/org/roam/Index.org")
 '(org-roam-mode t nil (org-roam))
 '(org-roam-server-mode t)
 '(org-roam-verbose nil)
 '(org-startup-align-all-tables t)
 '(org-startup-folded nil)
 '(org-startup-indented t)
 '(org-startup-with-inline-images t)
 '(org-startup-with-latex-preview t)
 '(org-superstar-cycle-headline-bullets nil)
 '(org-superstar-leading-fallback 32)
 '(org-tags-column -80)
 '(org-todo-keywords
   '((sequence "TODO(t)" "DOING(i)" "SOMEDAY(s)" "PHONE(p!)" "MØDE(m!)" "|" "DONE(d!)" "CANCEL(c@)")))
 '(org-track-ordered-property-with-tag t)
 '(preview-TeX-style-dir "/Users/niels/.emacs.d/straight/build/auctex/latex" t)
 '(reftex-plug-into-AUCTeX t t)
 '(sane-term-shell-command "/bin/zsh")
 '(set-mark-command-repeat-pop t)
 '(smartparens-global-mode t)
 '(sp-show-pair-from-inside t)
 '(xterm-mouse-mode t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(cfw:face-toolbar-button-off ((t (:foreground "gray76" :weight bold))))
 '(dashboard-banner-logo-titdelete-filele ((t (:family "Love LetterTW" :height 123))))
 '(lsp-ui-doc-background ((t (:background nil))))
 '(lsp-ui-doc-header ((t (:inherit (font-lock-string-face italic)))))
 '(org-journal-calendar-entry-face ((t (:foreground "#ee3b3b" :slant italic))))
 '(org-journal-calendar-scheduled-face ((t (:foreground "#c00000" :slant italic))))
 '(org-link ((t (:foreground "light blue" :underline t))))
 '(org-meta-line ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-pomodoro-mode-line ((t (:inherit warning))))
 '(org-pomodoro-mode-line-break ((t (:inherit success))))
 '(org-pomodoro-mode-line-overtime ((t (:inherit error))))
 '(org-property-value ((t (:inherit fixed-pitch))) t)
 '(org-roam-link ((t (:foreground "lime green" :underline t))))
 '(org-special-keyword ((t (:inherit (font-lock-comment-face fixed-pitch)))))
 '(org-table ((t (:inherit fixed-pitch))))
 '(spaceline-modified ((t (:foreground "black" :background "red"))))
 '(spaceline-unmodified ((t (:foreground "black" :background "gold")))))

