;;; Quickstart file to activate all packages at startup  -*- lexical-binding:t -*-
;; ¡¡ This file is autogenerated by `package-quickstart-refresh', DO NOT EDIT !!

(setq package-activated-list
      (append 'nil package-activated-list))

;; Local Variables:
;; version-control: never
;; no-update-autoloads: t
;; End:
